services:
  db:
    image: postgres:16.4-bullseye
    ports:
      - 5432:5432
    volumes:
      - /private/var/docker/var-lib-recipes-hub:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  elasticsearch:
    image: elasticsearch:8.15.0
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - http.cors.allow-origin=http://localhost:8080
      - http.cors.enabled=true

  web:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
      - elasticsearch
    volumes:
      - .:/app
    environment:
      - RAILS_ENV=development
      - POSTGRES_HOST=db
      - POSTGRES_DB=recipes_hub_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=password
      - ELASTICSEARCH_URL=http://elasticsearch:9200
